theme: jekyll-theme-minimal

lsi: false
safe: true
# source: https://github.com/zycalice/zycalice.github.io
# url: https://zycalice.github.io/
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  
includes: .md
keep_files: .md
